version: '3'
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow  # Dockerfile.mlflow을 사용해 빌드
    container_name: mlflow-server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=postgresql://mlflow:mlflow@mlflow-postgres/mlflow_db
    depends_on:
      - mlflow-postgres
    command: mlflow server --backend-store-uri postgresql://mlflow:mlflow@mlflow-postgres/mlflow_db --host 0.0.0.0 --port 5000

  mlflow-postgres:
    image: postgres
    container_name: mlflow-postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"

